description: 
pack: aws_boto3
enabled: true
entry_point: run.py
name: autoscaling_delete_launch_configuration
runner_type: run-python
parameters:
  action:
    default: delete_launch_configuration
    immutable: true
    type: string
  cls:
    default: autoscaling
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  region_name:
    type: string
  assume_role:
    type: string
  LaunchConfigurationName:
    type: string
    description: 'The name of the launch configuration.'
    required: true