description: 
pack: aws_boto3
enabled: true
entry_point: run.py
name: autoscaling_describe_launch_configurations
runner_type: run-python
parameters:
  action:
    default: describe_launch_configurations
    immutable: true
    type: string
  cls:
    default: autoscaling
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  region_name:
    type: string
  assume_role:
    type: string
  LaunchConfigurationNames:
    type: array
    description: "The launch configuration names. If you omit this parameter, all launch configurations are described."
  NextToken:
    type: string
    description: "The token for the next set of items to return. (You received this token from a previous call.)"
  MaxRecords:
    type: integer
    description: "The maximum number of items to return with this call. The default is 100."