description: 
pack: aws_boto3_s3
enabled: true
entry_point: run.py
name: s3_delete_bucket_metrics_configuration
runner_type: run-python
parameters:
  action:
    default: delete_bucket_metrics_configuration
    immutable: true
    type: string
  cls:
    default: s3
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  region_name:
    type: string
  assume_role:
    type: string
  Bucket:
    type: string
    description: "The name of the bucket containing the metrics configuration to delete."
    required: true
  Id:
    type: string
    description: "The ID used to identify the metrics configuration."
    required: true