description: 
pack: aws_boto3
enabled: true
entry_point: run.py
name: s3_delete_bucket_analytics_configuration
runner_type: run-python
parameters:
  action:
    default: delete_bucket_analytics_configuration
    immutable: true
    type: string
  cls:
    default: s3
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  region_name:
    type: string
  assume_role:
    type: string
  Bucket:
    type: string
    description: "The name of the bucket from which an analytics configuration is deleted."
    required: true
  Id:
    type: string
    description: "The identifier used to represent an analytics configuration."
    required: true