description: 
pack: aws_boto3
enabled: true
entry_point: run.py
name: sns_delete_platform_application
runner_type: run-python
parameters:
  action:
    default: delete_platform_application
    immutable: true
    type: string
  cls:
    default: sns
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  region_name:
    type: string
  assume_role:
    type: string
  PlatformApplicationArn:
    type: string
    description: 'PlatformApplicationArn of platform application object to delete.'
    required: true